[profile.default]
  libs = ["lib"]
  out = "out"
  src = "src"

  # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
  build_info = true
  evm_version = "cancun"
  
  ffi = true
  ast = true
  extra_output = ["storageLayout"]

  gas_limit = "18446744073709551615" 
  

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 100
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true

[dependencies]
openzeppelin-contracts = ">=5.0.0"